# Generated by Django 5.1.1 on 2024-10-04 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_feeding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateField(verbose_name='Feeding date'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('A', 'Apple'), ('B', 'Berry'), ('G', 'Grapes'), ('H', 'Hot Dog'), ('P', 'Pizza'), ('S', 'Sushi'), ('T', 'Tonkatsu')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='main_app.pokemon'),
        ),
    ]
